name: Forked Build Workflow

run-name: 'Forked Build Workflow'

on:
    push:
  

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    if: github.repository != 'ikmdev/${{github.event.repository.name}}' && github.event.repository.fork == 'true'
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: '21'
          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality